- name: Teams
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Add Microsoft APT package key
      become: yes
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
      when: not is_mac and not is_wsl

    - name: Add Teams APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main
        filename: teams
        update_cache: no
      register: apt_repository
      when: not is_mac and not is_wsl

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Teams (Linux)
      become: yes
      apt:
        package: teams
      when: not is_mac and not is_wsl

    # macOS

    - name: Install Teams (macOS)
      homebrew_cask:
        name: microsoft-teams
      when: is_mac
