- name: Ruby (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install Ruby gems
      command: ~/.rbenv/shims/gem install {{ item }}
      args:
        creates: ~/.rbenv/shims/{{ item }}
      loop:
        - readapt
        - solargraph

    - name: Install VS Code Extentions
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - castwide.ruby-debug
        - castwide.solargraph
