- name: git
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Add Git APT package repository
      become: yes
      apt_repository:
        repo: ppa:git-core/ppa
        filename: git
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install APT packages
      become: yes
      apt:
        package:
          - git
          - git-gui
          - git-lfs
          - gitk
        state: latest

    - name: Install ripgrep (18.04)
      become: yes
      apt:
        deb: https://github.com/BurntSushi/ripgrep/releases/download/11.0.1/ripgrep_11.0.1_amd64.deb
      when: ansible_distribution_release == 'bionic'

    - name: Install ripgrep (18.10 or later)
      become: yes
      apt:
        package: ripgrep
      when: ansible_distribution_release != 'bionic'
