- name: git (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is search('microsoft') }}

    - name: Install VS Code Extention
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - eamodio.gitlens
        - GitHub.vscode-pull-request-github
      when: not is_wsl
