- name: Add fortune to your startup shell script
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Install APT packages
      become: yes
      apt:
        package:
          - fortune
          - cowsay
          - lolcat

    - name: Add fortune to ~/.bashrc
      lineinfile:
        path: ~/.bashrc
        line: fortune | cowsay -W 70 -f "$(ls /usr/share/cowsay/cows | sort -R | head -1)" | lolcat
