- name: Insync
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Add Insync APT package key
      become: yes
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: ACCAF35C
      when: not is_wsl

    - name: Add Insync APT package repository
      become: yes
      apt_repository:
        repo: deb http://apt.insynchq.com/ubuntu bionic non-free contrib
        filename: insync
        update_cache: no
      register: apt_repository
      when: not is_wsl

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: not is_wsl and apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Insync
      become: yes
      apt:
        package:
          - insync
          - insync-nautilus
      when: not is_wsl
