- name: Google Backup and Sync
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    # Linux

    - name: Add Insync APT package key (Ubuntu)
      become: yes
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: ACCAF35C
      when: is_ubuntu and not is_wsl

    - name: Add Insync APT package repository (Ubuntu)
      become: yes
      apt_repository:
        repo: deb http://apt.insynchq.com/ubuntu bionic non-free contrib
        filename: insync
        update_cache: no
      register: apt_repository
      when: is_ubuntu and not is_wsl

    - name: Update APT package list (Ubuntu)
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Insync (Ubuntu)
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - insync
        - insync-nautilus
      when: is_ubuntu and not is_wsl

    # macOS

    - name: Install Google Backup and Sync (macOS)
      homebrew_cask:
        name: google-backup-and-sync
      when: is_mac
