- name: JetBrains
  hosts: 127.0.0.1
  connection: local

  vars:
    toolbox_ver: 1.14.5179

  tasks:
    - name: Determine if Toolbox is installed
      stat:
        path: /usr/local/bin/jetbrains-toolbox
      register: toolbox_path

    - block:

      # TODO: Find out if there is a canonical "latest" URL
      - name: Extract Toolbox
        unarchive:
          src: https://download.jetbrains.com/toolbox/jetbrains-toolbox-{{ toolbox_ver }}.tar.gz
          dest: /tmp
          creates: /tmp/jetbrains-toolbox-{{ toolbox_ver }}/jetbrains-toolbox

      - name: Install Toolbox
        become: yes
        copy:
          src: /tmp/jetbrains-toolbox-{{ toolbox_ver }}/jetbrains-toolbox
          dest: /usr/local/bin/jetbrains-toolbox
          mode: 0755
          remote_src: yes

      - name: Clean up /tmp/jetbrains-toolbox-{{ toolbox_ver }}
        file:
          path: /tmp/jetbrains-toolbox-{{ toolbox_ver }}
          state: absent

      - name: Launch Jetbrains Toolbox (first run experience)
        command: jetbrains-toolbox

      when: toolbox_path.stat.exists == False
