- name: QEMU/KVM
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    - set_fact: is_wsl={{ not is_mac and lookup('file', '/proc/version') is regex('(M|m)icrosoft') }}

    - name: Install QEMU/KVM
      become: yes
      apt:
        package: "{{ item }}"
      loop:
        - bridge-utils
        - libvirt-clients
        - libvirt-daemon-system
        - ovmf
        - qemu-kvm
        - virt-manager
      when: not is_mac and not is_wsl

    - name: Enable QEMU/KVM for current user
      become: yes
      user:
        name={{ lookup('env', "USER") }}
        groups=libvirt
        append=yes
      when: not is_mac and not is_wsl
