- name: GitHub (hub)
  hosts: 127.0.0.1
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  tasks:
    # Linux

    - name: Install hub CLI (Linux)
      become: yes
      command: snap install --classic hub
      args:
        creates: /snap/bin/hub
      when: not is_mac

    # macOS

    - name: Install hub CLI (macOS)
      homebrew:
        name: hub
      when: is_mac
