- name: .NET Core
  hosts: 127.0.0.1
  connection: local

  vars:
    dotnet_versions:
      - "2.1"
      - "3.0"
      - "3.1"
    dotnet_distro_release: "{{ ansible_distribution_release if ansible_distribution_release != 'eoan' else 'disco' }}"
    dotnet_distro_version: "{{ ansible_distribution_version if ansible_distribution_release != 'eoan' else '19.04' }}"

  tasks:
    - name: Add Microsoft APT package key
      become: yes
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc

    - name: Add Microsoft APT package repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/ubuntu/{{ dotnet_distro_version }}/prod {{ dotnet_distro_release }} main
        filename: microsoft-prod
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install .NET Core SDKs
      become: yes
      apt:
        package: dotnet-sdk-{{ item }}
      register: dotnet_sdk_installed
      loop: "{{ dotnet_versions }}"

    - name: Perform first-run experience
      command: dotnet new
      when: dotnet_sdk_installed.changed

    - name: Update environment for .NET Core
      blockinfile:
        path: ~/.bashrc
        marker: "### {mark} Ansible managed: .NET Core enhancement"
        block: |
          export PATH=$PATH:$HOME/.dotnet/tools
