- name: Ansible (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is search('microsoft') }}

    - name: Install VS Code Extention
      command: code --install-extension vscoss.vscode-ansible
      args:
        creates: ~/.vscode/extensions/vscoss.vscode-ansible-*/package.json
      when: not is_wsl
