- name: Mono
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is search('microsoft') }}

    - name: Add Mono APT package key
      become: yes
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

    - name: Add Mono APT package repository
      become: yes
      apt_repository:
        repo: deb https://download.mono-project.com/repo/ubuntu stable-bionic main
        filename: mono-official-stable
        update_cache: no
      register: apt_repository

    - name: Update APT package list
      become: yes
      apt:
        update_cache: yes
      when: apt_repository.changed
      register: apt_update
      retries: 5
      until: apt_update is success

    - name: Install Mono
      become: yes
      apt:
        package: mono-complete
      register: mono_install

    - name: Disable Mono binfmt on WSL
      become: yes
      shell: update-binfmts --disable cli
      when: is_wsl and mono_install.changed
