- name: Mono (VS Code)
  hosts: 127.0.0.1
  connection: local

  tasks:
    - set_fact: is_wsl={{ lookup('file', '/proc/version') is search('microsoft') }}

    - name: Install VS Code Extensions
      command: code --install-extension {{ item }}
      args:
        creates: ~/.vscode/extensions/{{ item }}-*/package.json
      loop:
        - ms-vscode.csharp     # C#
        - k--kato.docomment    # C# XML Documentation Comments
      when: not is_wsl
